-- Insert test data for membership status testing
INSERT INTO public.registrations (
  full_name,
  email,
  phone,
  city,
  iim_institute,
  graduation_year,
  profession,
  company,
  linkedin,
  interests,
  membership_type,
  transaction_id,
  status,
  membership_start_date,
  membership_end_date,
  last_payment_date,
  is_active
) VALUES
-- 1. Active Member (expires in 6 months)
(
  'John Active',
  'active@test.com',
  '+91-9876543210',
  'Mumbai',
  'IIM Ahmedabad',
  2020,
  'Software Engineer',
  'Tech Corp',
  'https://linkedin.com/in/johnactive',
  ARRAY['Technology', 'Networking'],
  'Annual',
  'TXN-ACTIVE-001',
  'approved',
  NOW() - INTERVAL '6 months',
  NOW() + INTERVAL '6 months',
  NOW() - INTERVAL '6 months',
  true
),
-- 2. Expiring Soon Member (expires in 15 days)
(
  'Sarah Expiring',
  'expiring@test.com',
  '+91-9876543211',
  'Delhi',
  'IIM Bangalore',
  2019,
  'Product Manager',
  'Product Inc',
  'https://linkedin.com/in/sarahexpiring',
  ARRAY['Entrepreneurship', 'Marketing'],
  'Annual',
  'TXN-EXPIRING-002',
  'approved',
  NOW() - INTERVAL '11 months 15 days',
  NOW() + INTERVAL '15 days',
  NOW() - INTERVAL '11 months 15 days',
  true
),
-- 3. Expired Member (expired 10 days ago)
(
  'Mike Expired',
  'expired@test.com',
  '+91-9876543212',
  'Bangalore',
  'IIM Calcutta',
  2018,
  'Consultant',
  'Consulting Firm',
  'https://linkedin.com/in/mikeexpired',
  ARRAY['Finance', 'Consulting'],
  'Annual',
  'TXN-EXPIRED-003',
  'approved',
  NOW() - INTERVAL '1 year 10 days',
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '1 year 10 days',
  true
),
-- 4. Lifetime Member (never expires)
(
  'Emma Lifetime',
  'lifetime@test.com',
  '+91-9876543213',
  'Chennai',
  'IIM Lucknow',
  2017,
  'Entrepreneur',
  'Own Startup',
  'https://linkedin.com/in/emmalifetime',
  ARRAY['Entrepreneurship', 'Technology'],
  'Lifetime',
  'TXN-LIFETIME-004',
  'approved',
  NOW() - INTERVAL '2 years',
  NULL,
  NOW() - INTERVAL '2 years',
  true
),
-- 5. Pending Application
(
  'Alex Pending',
  'pending@test.com',
  '+91-9876543214',
  'Hyderabad',
  'IIM Indore',
  2021,
  'Analyst',
  'Analytics Co',
  'https://linkedin.com/in/alexpending',
  ARRAY['Data Science', 'Analytics'],
  'Annual',
  'TXN-PENDING-005',
  'pending',
  NULL,
  NULL,
  NULL,
  false
),
-- 6. Rejected Application
(
  'Chris Rejected',
  'rejected@test.com',
  '+91-9876543215',
  'Pune',
  'IIM Kozhikode',
  2022,
  'Designer',
  'Design Studio',
  'https://linkedin.com/in/chrisrejected',
  ARRAY['Design', 'Creativity'],
  'Annual',
  'TXN-REJECTED-006',
  'rejected',
  NULL,
  NULL,
  NULL,
  false
);